# -*- coding: utf-8 -*-
import json, os

SRC_DIR = r"C:\Users\vppfe\Desktop\Agreement app\parsed_documents\parsed_documents"
OUT_DIR = r"C:\Users\vppfe\Desktop\Agreement app\agreements"
MANIFEST = r"C:\Users\vppfe\AppData\Local\Temp\claude\c--Users-vppfe-Desktop-Agreement-app\c207f2c0-10ea-4ffb-9cd6-e6629e6317eb\scratchpad\manifest_01.jsonl"

# filename -> (domain, key, title{uz,ru,en}, description{uz,ru,en}, low_confidence)
META = {
"151.json": ("real_estate", "house_part_sale_minor_buyer",
    {"uz":"Уй-жой бир қисмининг олди-сотди шартномаси (14 ёшдан ошган вояга етмаган сотиб олувчи номидан)",
     "ru":"Договор купли-продажи части дома (от имени несовершеннолетнего покупателя старше 14 лет)",
     "en":"Sale-purchase agreement for part of a house (on behalf of a minor buyer over 14 years old)"},
    {"uz":"Уй-жойнинг бир қисмини вояга етмаган (14 ёшдан катта) шахс номидан ота-онасининг розилиги билан сотиб олиш тартибини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор, регулирующий покупку части дома от имени несовершеннолетнего (старше 14 лет) с согласия родителей.",
     "en":"A notarized contract governing the purchase of part of a house on behalf of a minor (over 14) with parental consent."},
    False),
"152.json": ("business", "goods_supply_contract",
    {"uz":"Товарлар етказиб бериш шартномаси","ru":"Договор поставки товаров","en":"Goods supply agreement"},
    {"uz":"Сотувчи ва харидор корхоналар ўртасида қишлоқ хўжалик маҳсулотларини етказиб бериш шартлари, нархи ва жавобгарлигини белгилайдиган шартнома.",
     "ru":"Договор между предприятиями-продавцом и покупателем, определяющий условия, цену и ответственность при поставке сельхозпродукции.",
     "en":"An agreement between a seller and buyer enterprise setting the terms, price, and liability for delivery of agricultural goods."},
    False),
"153.json": ("real_estate", "house_sale_no_registered_residents_deaf_seller",
    {"uz":"Уй-жой олди-сотди шартномаси (хонадонда пропискада турувчи шахслар бўлмаган ҳолда, сурдо таржимон иштирокида)",
     "ru":"Договор купли-продажи дома (без прописанных лиц, с участием сурдопереводчика)",
     "en":"House sale agreement (no registered residents, with sign-language interpreter)"},
    {"uz":"Уйда рўйхатда турувчи шахслар йўқлигини тасдиқловчи ва сотувчи кар-соқов бўлганда сурдо таржимон иштирокини назарда тутувчи уй-жой сотиш шартномаси.",
     "ru":"Договор продажи дома, подтверждающий отсутствие зарегистрированных жильцов и предусматривающий участие сурдопереводчика при глухонемоте продавца.",
     "en":"A house sale contract confirming no registered residents in the property and providing for a sign-language interpreter when the seller is deaf-mute."},
    False),
"154.json": ("business", "gratuitous_use_agreement",
    {"uz":"Текин фойдаланиш шартномаси","ru":"Договор безвозмездного пользования","en":"Gratuitous (free) use agreement"},
    {"uz":"Мол-мулкни бир тарафдан иккинчи тарафга вақтинчалик текин фойдаланиш учун бериш шартлари ва тарафлар мажбуриятларини белгилайдиган шартнома.",
     "ru":"Договор, определяющий условия временной безвозмездной передачи имущества в пользование и обязанности сторон.",
     "en":"A contract setting the terms for temporary free (gratuitous) use of property and the obligations of both parties."},
    False),
"155.json": ("real_estate", "house_sale_minor_coowners",
    {"uz":"14 ёшгача ва 14-18 ёшдаги вояга етмаган мулкдорлар улуши мавжуд уй-жой олди-сотди шартномаси",
     "ru":"Договор купли-продажи дома с долями несовершеннолетних собственников (до 14 и от 14 до 18 лет)",
     "en":"House sale agreement with shares belonging to minor co-owners (under 14 and 14-18 years old)"},
    {"uz":"Уй-жойда 14 ёшгача ва 14-18 ёшдаги вояга етмаган мулкдорларнинг улуши мавжуд бўлганда, васийлик органи вакили иштирокида уй-жой сотиш тартибини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор, регулирующий продажу дома при наличии долей несовершеннолетних собственников с участием представителя органа опеки.",
     "en":"A notarized contract regulating the sale of a house when minor co-owners hold shares, involving a guardianship authority representative."},
    False),
"156.json": ("government", "government_goods_supply_contract",
    {"uz":"Товарлар етказиб бериш бўйича давлат контракти","ru":"Государственный контракт на поставку товаров","en":"State contract for supply of goods"},
    {"uz":"Ижрочи корхона билан давлат буюртмачиси ўртасида товарларни давлат эҳтиёжлари учун етказиб бериш шартларини белгилайдиган контракт.",
     "ru":"Контракт между исполнителем и государственным заказчиком, определяющий условия поставки товаров для государственных нужд.",
     "en":"A contract between a supplier and a state customer setting terms for delivering goods for state needs."},
    False),
"166.json": ("real_estate", "house_sale_via_representative",
    {"uz":"Уй-жой олди-сотди шартномаси (ишончли вакил орқали)","ru":"Договор купли-продажи дома (через доверенное лицо)","en":"House sale agreement (through an authorized representative)"},
    {"uz":"Сотувчи номидан ишончнома асосида ҳаракат қилувчи вакил иштирокида уй-жойни сотиш шартларини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор продажи дома, заключаемый представителем продавца, действующим по доверенности.",
     "en":"A notarized house sale contract executed by a representative acting under a power of attorney on behalf of the seller."},
    False),
"167.json": ("construction", "individual_house_construction_customer_agreement",
    {"uz":"Уй-жой қуришга буюртмачи функцияларини амалга ошириш тўғрисида шартнома",
     "ru":"Договор о выполнении функций заказчика при строительстве индивидуального жилого дома",
     "en":"Agreement on performing customer (developer) functions for individual house construction"},
    {"uz":"Якка тартибдаги уй-жой қурувчи билан буюртмачи ташкилот ўртасида қурилишни молиялаштириш, ипотека кредити ва объектни топшириш шартларини белгиловчи шартнома.",
     "ru":"Договор между индивидуальным застройщиком и организацией-заказчиком, устанавливающий условия финансирования строительства, ипотечного кредита и сдачи объекта.",
     "en":"A contract between an individual house builder and a developer organization defining construction financing, mortgage terms, and handover of the property."},
    False),
"168.json": ("real_estate", "house_sale_with_registered_residents",
    {"uz":"Уй-жой олди-сотди шартномаси (уй-жойда пропискада турувчи шахслар бўлган ҳолда)",
     "ru":"Договор купли-продажи дома (при наличии прописанных лиц)",
     "en":"House sale agreement (with registered residents present)"},
    {"uz":"Сотилаётган уй-жойда рўйхатда турувчи шахслар мавжуд бўлганда, уларнинг маълум муддатда рўйхатдан чиқиш мажбуриятини назарда тутувчи уй-жой сотиш шартномаси.",
     "ru":"Договор продажи дома, предусматривающий обязательство зарегистрированных жильцов сняться с регистрационного учёта в установленный срок.",
     "en":"A house sale contract that requires registered residents of the property to deregister within a set deadline."},
    False),
"172.json": ("real_estate", "house_rental_agreement",
    {"uz":"Уй-жойни ижарага бериш шартномаси","ru":"Договор аренды жилого дома","en":"House rental (lease) agreement"},
    {"uz":"Уй-жой эгаси билан ижарачи ўртасида уй-жойдан вақтинча ҳақ эвазига фойдаланиш шартлари, ижара ҳақи ва тарафлар мажбуриятларини белгилайдиган шартнома.",
     "ru":"Договор между владельцем и арендатором дома, определяющий условия временного возмездного пользования, размер арендной платы и обязанности сторон.",
     "en":"A contract between a homeowner and a tenant setting terms for temporary paid use of the house, rent amount, and obligations of both parties."},
    False),
"181.json": ("real_estate", "hoa_nonresidential_owner_agreement",
    {"uz":"Хусусий уй-жой мулкдорлари ширкати билан кўп квартирали уйдаги нотурар жой мулкдори ўртасидаги шартнома",
     "ru":"Договор между товариществом собственников жилья и владельцем нежилого помещения в многоквартирном доме",
     "en":"Agreement between a homeowners' association and the owner of a non-residential premise in an apartment building"},
    {"uz":"Кўп квартирали уйдаги умумий мулкни сақлаш бўйича хизматлар ва мажбурий бадаллар тартибини белгилайдиган ХУЖМШ билан нотурар жой мулкдори ўртасидаги шартнома.",
     "ru":"Договор между ТСЖ и владельцем нежилого помещения, определяющий порядок содержания общего имущества и обязательных взносов.",
     "en":"A contract between an HOA and the owner of a non-residential unit defining common-property maintenance services and mandatory contribution rules."},
    False),
"184.json": ("employment", "employment_contract_amendment_agreement",
    {"uz":"Меҳнат шартномасига ўзгартириш киритиш тўғрисида келишув","ru":"Соглашение о внесении изменений в трудовой договор","en":"Agreement to amend an employment contract"},
    {"uz":"Ходимнинг лавозими ёки ташкилот номи ўзгарганда меҳнат шартномасига тегишли ўзгартиришлар киритиш тартибини белгилайдиган келишув.",
     "ru":"Соглашение, устанавливающее порядок внесения изменений в трудовой договор при изменении должности работника или наименования организации.",
     "en":"An agreement establishing the procedure for amending an employment contract when an employee's position or the organization's name changes."},
    False),
"185.json": ("employment", "probation_termination_warning_letter",
    {"uz":"Огоҳлантириш хати (меҳнат шартномасини бекор қилиш тўғрисида)","ru":"Предупредительное письмо о расторжении трудового договора","en":"Warning letter on termination of employment contract"},
    {"uz":"Ходимнинг дастлабки синов муддати натижаси қониқарсиз деб топилганда, унинг меҳнат шартномаси бекор қилиниши ҳақида ёзма огоҳлантириш хати.",
     "ru":"Письменное предупреждение работнику о расторжении трудового договора в связи с неудовлетворительным результатом испытательного срока.",
     "en":"A written warning notifying an employee that their employment contract will be terminated due to an unsatisfactory probation-period result."},
    False),
"186.json": ("employment", "employment_termination_mutual_agreement",
    {"uz":"Меҳнат шартномасини бекор қилиш тўғрисида келишув","ru":"Соглашение о расторжении трудового договора","en":"Agreement to terminate an employment contract by mutual consent"},
    {"uz":"Иш берувчи ва ходим ўртасида меҳнат шартномасини тарафларнинг ўзаро келишувига асосан бекор қилиш шартларини белгилайдиган ҳужжат.",
     "ru":"Документ, устанавливающий условия прекращения трудового договора между работодателем и работником по взаимному согласию сторон.",
     "en":"A document setting the terms for ending an employment contract between employer and employee by mutual agreement."},
    False),
"188.json": ("employment", "legal_officer_appointment_coordination_proposal",
    {"uz":"Юридик хизмат ходимини лавозимга тайинлашни адлия органи билан келишиш тўғрисида тақдимнома",
     "ru":"Представление о согласовании назначения работника юридической службы с органом юстиции",
     "en":"Proposal for coordinating the appointment of a legal service employee with the justice authority"},
    {"uz":"Ташкилот юридик хизмати ходимини лавозимга тайинлашдан олдин номзодни адлия бўлими билан келишиш учун юборилувчи расмий тақдимнома.",
     "ru":"Официальное представление, направляемое в отдел юстиции для согласования кандидатуры перед назначением работника юридической службы на должность.",
     "en":"An official proposal sent to the justice department to coordinate a candidate before appointing a legal service employee to a position."},
    False),
"189.json": ("vehicle", "vehicle_exchange_agreement",
    {"uz":"Автотранспорт воситасини айирбошлаш шартномаси","ru":"Договор мены автотранспортного средства","en":"Vehicle exchange (barter) agreement"},
    {"uz":"Икки тараф ўртасида ўзларига тегишли автотранспорт воситаларини ўзаро айирбошлаш шартлари ва баҳосини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор, определяющий условия и оценочную стоимость взаимного обмена автотранспортными средствами между двумя сторонами.",
     "en":"A notarized contract defining the terms and valuation for two parties exchanging vehicles they own."},
    False),
"191.json": ("employment", "annual_leave_schedule",
    {"uz":"Меҳнат таътиллари жадвали","ru":"График трудовых отпусков","en":"Annual leave (vacation) schedule"},
    {"uz":"Ташкилот ходимларининг йил давомида меҳнат таътилига чиқиш саналарини белгилайдиган ва тасдиқланадиган жадвал ҳужжати.",
     "ru":"Документ-график, устанавливающий и утверждающий даты выхода работников организации в трудовой отпуск в течение года.",
     "en":"A schedule document setting and approving the dates on which an organization's employees will take their annual leave."},
    False),
"192.json": ("employment", "labor_record_book_temporary_receipt",
    {"uz":"Тилхат (Меҳнат дафтарчасини вақтинчалик олиб туриш тўғрисида)","ru":"Расписка о временном получении трудовой книжки","en":"Receipt for temporary custody of a labor record book"},
    {"uz":"Ходимнинг нотариал тасдиқлаш ёки нусха олиш мақсадида меҳнат дафтарчасини вақтинча олгани ва қайтариш муддатини тасдиқловчи тилхат.",
     "ru":"Расписка, подтверждающая временное получение работником трудовой книжки для нотариального заверения или снятия копии и срок её возврата.",
     "en":"A receipt confirming an employee's temporary custody of a labor record book for notarization or copying, and the return deadline."},
    False),
"195.json": ("employment", "personnel_file_folder_cover",
    {"uz":"Шахсий йиғма жилди (муқова ва ички рўйхат)","ru":"Личное дело (обложка и внутренняя опись)","en":"Personnel file folder cover sheet and internal inventory"},
    {"uz":"Ходимнинг шахсий йиғма жилдида сақланадиган ҳужжатларнинг ички рўйхати ва жилднинг сақлаш маълумотларини қайд этувчи ҳужжат.",
     "ru":"Документ с обложкой и внутренней описью, фиксирующий документы, хранящиеся в личном деле сотрудника, и сроки хранения.",
     "en":"A cover-sheet document with an internal inventory recording the documents kept in an employee's personnel file and its retention details."},
    False),
"201.json": ("employment", "collective_agreement_approval_minutes",
    {"uz":"Жамоа шартномасини маъқуллаш тўғрисида меҳнат жамоаси умумий йиғилиши баёни",
     "ru":"Протокол общего собрания трудового коллектива об одобрении коллективного договора",
     "en":"Minutes of the general staff meeting approving the collective bargaining agreement"},
    {"uz":"Ташкилот меҳнат жамоаси йиғилишида жамоа шартномаси лойиҳасини муҳокама қилиш ва овозга қўйиш натижаларини қайд этувчи баённома.",
     "ru":"Протокол, фиксирующий обсуждение проекта коллективного договора и результаты голосования на собрании трудового коллектива.",
     "en":"Minutes recording the discussion and voting results on a draft collective bargaining agreement at a staff general meeting."},
    False),
"202.json": ("business", "fixed_asset_acceptance_act",
    {"uz":"Товар моддий бойликни топшириш ва қабул қилиш тўғрисида далолатнома",
     "ru":"Акт приёма-передачи товарно-материальных ценностей","en":"Acceptance-transfer act for inventory/fixed assets"},
    {"uz":"Ташкилот балансидаги ускуна ёки асосий воситани бир масъул шахсдан бошқасига топшириш ва қабул қилиш жараёнини расмийлаштирувчи далолатнома.",
     "ru":"Акт, оформляющий процесс передачи и приёма оборудования или основного средства с баланса организации от одного ответственного лица другому.",
     "en":"An act formalizing the handover and acceptance of equipment or a fixed asset on an organization's balance sheet between responsible persons."},
    False),
"203.json": ("construction", "construction_contract_general",
    {"uz":"Пудрат шартномаси (объект қурилиши тўғрисида)","ru":"Договор подряда на строительство объекта","en":"General construction contract"},
    {"uz":"Буюртмачи ва пудратчи ўртасида объект қурилиши муддати, қиймати, аванс, кафолат ва жарима шартларини белгилайдиган пудрат шартномаси.",
     "ru":"Договор подряда между заказчиком и подрядчиком, устанавливающий сроки, стоимость строительства, авансирование, гарантию и штрафные санкции.",
     "en":"A construction contract between a customer and a contractor defining timelines, cost, advance payment, warranty, and penalty terms."},
    False),
"211.json": ("employment", "labor_record_book_destruction_act",
    {"uz":"Меҳнат дафтарчаларини йўқ қилиш тўғрисида далолатнома","ru":"Акт об уничтожении трудовых книжек","en":"Act on destruction of labor record books"},
    {"uz":"Архивда белгиланган муддатдан ортиқ сақланган эгасиз меҳнат дафтарчаларини комиссия томонидан йўқ қилиш жараёнини расмийлаштирувчи далолатнома.",
     "ru":"Акт, оформляющий процесс уничтожения комиссией невостребованных трудовых книжек, хранившихся в архиве сверх установленного срока.",
     "en":"An act formalizing a commission's destruction of unclaimed labor record books that were archived beyond the required retention period."},
    False),
"212.json": ("business", "fixed_asset_handover_act",
    {"uz":"Товар моддий бойликни топшириш-қабул қилиш тўғрисида далолатнома (иккинчи шакл)",
     "ru":"Акт приёма-передачи товарно-материальных ценностей (второй вариант)",
     "en":"Inventory/fixed-asset handover act (alternate template)"},
    {"uz":"Буйруққа асосан ташкилот балансидаги моддий бойликни бир шахсдан бошқасига моддий жавобгарлик асосида топшириш далолатномаси.",
     "ru":"Акт передачи материальных ценностей с баланса организации от одного лица другому на основании приказа о материальной ответственности.",
     "en":"An act, issued pursuant to an order, transferring an organization's inventory item between two materially responsible persons."},
    False),
"214.json": ("family", "child_travel_abroad_obligation_letter",
    {"uz":"Вояга етмаган болани чет элга кузатиб бориш ва олиб келиш тўғрисида мажбуриятнома",
     "ru":"Обязательство о сопровождении несовершеннолетнего ребёнка за границу и обратно",
     "en":"Obligation letter for escorting a minor child abroad and back"},
    {"uz":"Ота-онадан бирининг вояга етмаган фарзандини чет элга олиб бориб, белгиланган муддатда қайтариб келтириш мажбуриятини нотариал тасдиқловчи ҳужжат.",
     "ru":"Нотариально удостоверенный документ об обязательстве одного из родителей вывезти несовершеннолетнего ребёнка за границу и вернуть его в установленный срок.",
     "en":"A notarized document obligating a parent to take a minor child abroad and bring them back within a set period."},
    False),
"215.json": ("business", "contract_termination_agreement",
    {"uz":"Шартномани бекор қилиш ҳақидаги келишув","ru":"Соглашение о расторжении договора","en":"Agreement to terminate a contract"},
    {"uz":"Буюртмачи ва ижрочи ўртасидаги мавжуд шартномани муайян сабабга кўра муддатидан олдин бекор қилиш шартларини белгилайдиган келишув.",
     "ru":"Соглашение, устанавливающее условия досрочного расторжения действующего договора между заказчиком и исполнителем по определённой причине.",
     "en":"An agreement setting the terms for early termination of an existing contract between a customer and a contractor for a stated reason."},
    False),
"216.json": ("finance", "notary_deposit_receipt",
    {"uz":"Пул суммалари ва қимматбаҳо қоғозларни депозитга қабул қилиш квитанцияси",
     "ru":"Квитанция о принятии денежных сумм и ценных бумаг в депозит нотариуса",
     "en":"Receipt for money and securities accepted into notary deposit"},
    {"uz":"Қарздордан қарз шартномаси бўйича тўланадиган пул суммасини нотариус депозитига қабул қилинганлигини тасдиқловчи квитанция.",
     "ru":"Квитанция, подтверждающая принятие нотариусом на депозит денежной суммы, причитающейся по договору займа.",
     "en":"A receipt confirming a notary's acceptance into deposit of a sum owed under a loan agreement."},
    False),
"217.json": ("employment", "probation_period_failure_act",
    {"uz":"Дастлабки синов натижаси тўғрисида далолатнома","ru":"Акт о результатах испытательного срока","en":"Act on the results of a probationary period"},
    {"uz":"Ходимнинг синов муддати давомида топшириқларни қониқарли бажара олмаганлигини қайд этувчи ва меҳнат шартномасини бекор қилишга асос бўлувчи далолатнома.",
     "ru":"Акт, фиксирующий неудовлетворительное выполнение работником заданий в течение испытательного срока, служащий основанием для расторжения трудового договора.",
     "en":"An act recording an employee's unsatisfactory performance during the probation period, serving as grounds for termination of employment."},
    False),
"218.json": ("employment", "full_material_liability_agreement",
    {"uz":"Тўлиқ моддий жавобгарлик тўғрисида шартнома","ru":"Договор о полной материальной ответственности","en":"Agreement on full material (financial) liability"},
    {"uz":"Иш берувчи ходимга ишониб топширган моддий бойликлар учун унинг тўлиқ моддий жавобгарлигини белгилайдиган меҳнат шартномасига илова.",
     "ru":"Приложение к трудовому договору, устанавливающее полную материальную ответственность работника за вверенные ему товарно-материальные ценности.",
     "en":"An addendum to an employment contract establishing an employee's full financial liability for inventory entrusted to them."},
    False),
"219.json": ("family", "child_travel_consent_with_escort",
    {"uz":"Вояга етмаган боланинг чет элга кузатувчи билан бориб-келишига розилик аризаси",
     "ru":"Заявление о согласии на выезд несовершеннолетнего ребёнка за границу в сопровождении",
     "en":"Application for consent to a minor child's escorted trip abroad"},
    {"uz":"Ота-онадан бирининг фарзанди иккинчи ота-она ҳамроҳлигида чет элга бориб-келишига розилик билдирувчи нотариал ариза.",
     "ru":"Нотариальное заявление одного из родителей о согласии на выезд ребёнка за границу в сопровождении второго родителя.",
     "en":"A notarized application by one parent consenting to a child's trip abroad accompanied by the other parent."},
    False),
"223.json": ("inheritance", "will_notarial_endorsement",
    {"uz":"Васиятноманинг тасдиқлов ёзуви","ru":"Удостоверительная надпись на завещании","en":"Notarial endorsement of a will"},
    {"uz":"Нотариус томонидан васиятномани тасдиқлаш, реестрга қайд этиш ва давлат божини ундиришни расмийлаштирувчи тасдиқлов ёзуви.",
     "ru":"Удостоверительная надпись нотариуса, оформляющая удостоверение завещания, его регистрацию в реестре и взимание госпошлины.",
     "en":"A notary's endorsement formalizing certification of a will, its registry entry, and collection of the state fee."},
    False),
"225.json": ("inheritance", "secret_will_notarial_endorsement",
    {"uz":"Махфий васиятноманинг тасдиқлов ёзуви","ru":"Удостоверительная надпись на закрытом завещании","en":"Notarial endorsement of a closed (secret) will"},
    {"uz":"Васият қилувчи ва икки гувоҳ иштирокида ёпиқ хатжилдга солинган махфий васиятномани нотариус тасдиқлаганлигини қайд этувчи ёзув.",
     "ru":"Запись, удостоверяющая удостоверение нотариусом закрытого завещания, запечатанного в конверте в присутствии завещателя и двух свидетелей.",
     "en":"A notation certifying a notary's certification of a closed will sealed in an envelope in the presence of the testator and two witnesses."},
    False),
"226.json": ("inheritance", "will_signed_by_proxy_endorsement",
    {"uz":"Ўз қўли билан имзолай олмаган шахс номидан бошқа шахс имзолаган васиятноманинг тасдиқлов ёзуви",
     "ru":"Удостоверительная надпись на завещании, подписанном другим лицом за завещателя, не способного подписать сам",
     "en":"Notarial endorsement of a will signed by proxy for a testator unable to sign personally"},
    {"uz":"Жисмоний нуқсон, касаллик ёки саводсизлик сабабли ўзи имзолай олмаган васият қилувчи ўрнига бошқа шахс имзолаган васиятномани тасдиқлаш ёзуви.",
     "ru":"Удостоверительная надпись на завещании, подписанном по просьбе завещателя другим лицом ввиду физического недостатка, болезни или неграмотности.",
     "en":"An endorsement certifying a will signed by another person on behalf of a testator unable to sign due to physical impairment, illness, or illiteracy."},
    False),
"229.json": ("employment", "individual_full_material_liability_agreement",
    {"uz":"Якка тартибдаги тўлиқ моддий жавобгарлик тўғрисида шартнома","ru":"Договор об индивидуальной полной материальной ответственности","en":"Individual full material liability agreement"},
    {"uz":"Ходимга алоҳида ишониб топширилган моддий қимматликлар сақланиши учун унинг якка тартибдаги тўлиқ моддий жавобгарлигини белгилайдиган шартнома.",
     "ru":"Договор, устанавливающий индивидуальную полную материальную ответственность работника за сохранность вверенных ему ценностей.",
     "en":"A contract establishing an individual employee's full financial liability for the safekeeping of assets entrusted specifically to them."},
    False),
"232.json": ("loan", "vehicle_pledge_loan_agreement",
    {"uz":"Гаров шартномаси (кредит таъминоти учун автотранспорт воситалари гаровга қўйилиши)",
     "ru":"Договор залога (обеспечение кредита автотранспортными средствами)",
     "en":"Pledge agreement (vehicles pledged as loan collateral)"},
    {"uz":"Банк кредитини таъминлаш мақсадида қарз олувчи ва гаровга қўювчилар томонидан автотранспорт воситаларини банкка гаровга қўйиш шартларини белгилайдиган шартнома.",
     "ru":"Договор, устанавливающий условия передачи автотранспортных средств в залог банку заёмщиком и залогодателями в обеспечение банковского кредита.",
     "en":"A contract setting the terms under which a borrower and pledgors pledge vehicles to a bank to secure a loan."},
    False),
"234.json": ("inheritance", "funeral_expense_reimbursement_order",
    {"uz":"Мерос қолдирувчини дафн этиш билан боғлиқ харажатларни қоплаш тўғрисида фармойиш",
     "ru":"Распоряжение о возмещении расходов, связанных с погребением наследодателя",
     "en":"Order for reimbursement of expenses related to burial of the deceased"},
    {"uz":"Марҳумни дафн этган шахсга унинг банкдаги маблағларидан дафн харажатларини қоплаш учун пул ажратилишини буюрувчи нотариус фармойиши.",
     "ru":"Распоряжение нотариуса о выделении лицу, организовавшему похороны, средств со счёта умершего для возмещения расходов на погребение.",
     "en":"A notary's order directing that funds from the deceased's bank account be released to the person who arranged the burial, to cover funeral expenses."},
    False),
"235.json": ("inheritance", "surviving_spouse_share_certificate_application",
    {"uz":"Умумий мол-мулкдаги улушга бўлган мулк ҳуқуқи тўғрисида гувоҳнома бериш ҳақида тирик қолган турмуш ўртоқнинг аризаси",
     "ru":"Заявление пережившего супруга о выдаче свидетельства о праве собственности на долю в общем имуществе",
     "en":"Application by a surviving spouse for a certificate of ownership share in joint marital property"},
    {"uz":"Вафот этган турмуш ўртоғи номига расмийлаштирилган умумий мол-мулкдаги ўз улушига мулк ҳуқуқи гувоҳномаси беришни сўраб тирик қолган турмуш ўртоқ томонидан нотариусга берилувчи ариза.",
     "ru":"Заявление, подаваемое пережившим супругом нотариусу, с просьбой выдать свидетельство о праве собственности на его долю в общем имуществе, оформленном на имя умершего супруга.",
     "en":"An application filed by a surviving spouse with a notary requesting a certificate of ownership for their share of joint property registered in the deceased spouse's name."},
    False),
"238.json": ("inheritance", "additional_inheritance_certificate_application",
    {"uz":"Илгари берилган гувоҳномага қўшимча равишда меросга бўлган ҳуқуқ тўғрисида гувоҳнома бериш ҳақида ариза",
     "ru":"Заявление о выдаче дополнительного свидетельства о праве на наследство к ранее выданному",
     "en":"Application for an additional certificate of inheritance right supplementing one already issued"},
    {"uz":"Илгари гувоҳнома берилгандан кейин топилган қўшимча мерос мол-мулкка (масалан, банк ҳисобварағига) нисбатан янги гувоҳнома беришни сўраб берилувчи ариза.",
     "ru":"Заявление с просьбой выдать новое свидетельство на дополнительно обнаруженное наследственное имущество (например, банковский счёт), выявленное после выдачи первого свидетельства.",
     "en":"An application requesting a new certificate for additional inherited property (e.g., a bank account) discovered after the first certificate was issued."},
    False),
"240.json": ("inheritance", "inheritance_preservation_reward_order",
    {"uz":"Мерос мол-мулкни сақлаганлик учун тақдирлаш тўғрисида фармойиш","ru":"Распоряжение о вознаграждении за сохранение наследственного имущества","en":"Order awarding reward for preservation of inheritance property"},
    {"uz":"Мерос мол-мулкни қўриқлаган ва бошқарган шахсга унинг хизматлари учун марҳумнинг банк маблағидан мукофот тўланишини буюрувчи нотариус фармойиши.",
     "ru":"Распоряжение нотариуса о выплате вознаграждения со счёта умершего лицу, охранявшему и управлявшему наследственным имуществом.",
     "en":"A notary's order directing payment of a reward from the deceased's bank funds to the person who guarded and managed the inheritance property."},
    False),
"241.json": ("family", "spousal_consent_property_disposal_application",
    {"uz":"Эр ва хотиннинг умумий мол-мулкини сотишга, гаровга қўйишга, ижарага беришга розилик аризаси",
     "ru":"Заявление о согласии супруга на продажу, залог, сдачу в аренду общего имущества",
     "en":"Spousal consent application for selling, mortgaging, or leasing joint marital property"},
    {"uz":"Турмуш ўртоқлардан бирининг иккинчиси номига расмийлаштирилган умумий уй-жойни истаган шартларда сотиш, гаровга қўйиш ёки ижарага беришга розилигини билдирувчи нотариал ариза.",
     "ru":"Нотариальное заявление одного из супругов о согласии на продажу, залог или сдачу в аренду совместно нажитого жилья, оформленного на имя другого супруга.",
     "en":"A notarized application by one spouse consenting to the sale, pledge, or lease of jointly acquired housing registered in the other spouse's name."},
    False),
"242.json": ("inheritance", "marital_property_share_certificate_application",
    {"uz":"Эр-хотиннинг умумий мол-мулкидаги улушга бўлган мулк ҳуқуқи тўғрисидаги гувоҳнома бериш ҳақидаги ариза",
     "ru":"Заявление о выдаче свидетельства о праве собственности на долю в общем имуществе супругов",
     "en":"Application for a certificate of ownership share in spouses' joint property"},
    {"uz":"Никоҳ давомида орттирилган ва бир томон номига расмийлаштирилган уй-жойдаги ҳар икки тарафнинг улуш ҳуқуқини тасдиқловчи гувоҳнома беришни сўраб иккала турмуш ўртоқ томонидан берилувчи ариза.",
     "ru":"Заявление, подаваемое обоими супругами, с просьбой выдать свидетельство, подтверждающее долю каждого в жилье, приобретённом в браке и оформленном на имя одного из них.",
     "en":"A joint application by both spouses requesting a certificate confirming each spouse's share in housing acquired during marriage and registered to one of them."},
    False),
"247.json": ("vehicle", "vehicle_pledge_prohibition_notice",
    {"uz":"Гаров шартномаси бўйича автотранспорт воситасини тасарруф этишни тақиқлаш тўғрисида нотариал тақиқнома",
     "ru":"Нотариальный запрет на отчуждение автотранспортного средства по договору залога",
     "en":"Notarial prohibition on disposal of a vehicle pledged under a loan contract"},
    {"uz":"Кредит бўйича мажбурият тўлиқ бажарилмагунча гаровга қўйилган автотранспорт воситасини бошқа шахсга ўтказишни тақиқловчи нотариус ҳужжати.",
     "ru":"Документ нотариуса, запрещающий передачу заложенного автотранспортного средства третьим лицам до полного исполнения кредитных обязательств.",
     "en":"A notarial document prohibiting transfer of a pledged vehicle to third parties until the loan obligation is fully repaid."},
    False),
"251.json": ("vehicle", "vehicle_rental_agreement",
    {"uz":"Автотранспорт воситасини ижарага бериш шартномаси","ru":"Договор аренды автотранспортного средства","en":"Vehicle rental (lease) agreement"},
    {"uz":"Автомобиль эгаси билан ижарачи ўртасида транспорт воситасидан вақтинча фойдаланиш муддати, ижара ҳақи ва тарафлар мажбуриятларини белгиловчи нотариал шартнома.",
     "ru":"Нотариальный договор между владельцем автомобиля и арендатором, определяющий срок пользования транспортным средством, размер арендной платы и обязанности сторон.",
     "en":"A notarized contract between a vehicle owner and a lessee setting the rental period, fee, and obligations of both parties."},
    False),
"253.json": ("education", "foreign_student_magistracy_admission_application",
    {"uz":"Тошкент давлат юридик университети магистратурасига хорижий фуқароларни ўқишга қабул қилиш тўғрисида ариза",
     "ru":"Заявление о приёме иностранных граждан в магистратуру Ташкентского государственного юридического университета",
     "en":"Application for admission of foreign citizens to TSUL's master's (magistracy) program"},
    {"uz":"Хорижий фуқаронинг Тошкент давлат юридик университети магистратурасига ўқишга кириш учун суҳбатда қатнашишга рухсат сўраб берадиган аризаси.",
     "ru":"Заявление иностранного гражданина с просьбой допустить его к вступительному собеседованию для поступления в магистратуру ТГЮУ.",
     "en":"An application by a foreign citizen requesting admission to the entrance interview for TSUL's master's program."},
    False),
"254.json": ("inheritance", "compulsory_share_certificate_application",
    {"uz":"Меҳнатга қобилиятсиз турмуш ўртоқнинг мажбурий улуш бўйича меросга ҳуқуқ тўғрисида гувоҳнома олиш ҳақидаги аризаси",
     "ru":"Заявление нетрудоспособного супруга о выдаче свидетельства о праве на обязательную долю в наследстве",
     "en":"Application by an incapacitated spouse for a certificate of the compulsory (mandatory) inheritance share"},
    {"uz":"Васиятномада кўрсатилмаган, лекин меҳнатга қобилияти йўқлиги сабабли мажбурий улушга ҳақли турмуш ўртоқ томонидан берилувчи мерос гувоҳномаси олиш аризаси.",
     "ru":"Заявление о получении свидетельства о наследстве, подаваемое нетрудоспособным супругом, не упомянутым в завещании, но имеющим право на обязательную долю.",
     "en":"An application for an inheritance certificate filed by an incapacitated spouse who was not named in the will but is entitled to a compulsory share."},
    False),
"255.json": ("employment", "self_employment_certificate_application",
    {"uz":"Ўзини ўзи банд қилувчининг вақтинчалик меҳнат гувоҳномасини бериш учун аризаси",
     "ru":"Заявление самозанятого лица о выдаче временного трудового свидетельства",
     "en":"Application by a self-employed person for a temporary labor certificate"},
    {"uz":"Ўзини ўзи банд қилган шахснинг фаолият тури ва муддатини кўрсатиб, Бандликка кўмаклашиш марказидан вақтинча меҳнат гувоҳномаси олиш ва рўйхатдан ўтиш аризаси.",
     "ru":"Заявление самозанятого лица в Центр содействия занятости о выдаче временного трудового свидетельства с указанием вида деятельности и срока.",
     "en":"An application to an employment assistance center by a self-employed person requesting a temporary labor certificate, stating the activity type and duration."},
    False),
"256.json": ("finance", "fx_collateral_loan_application",
    {"uz":"Ўзгармас фоиз ставка бўйича чет эл валютасини гаровга қўйган ҳолда кредит олиш тўғрисида ариза",
     "ru":"Заявление на получение кредита под залог иностранной валюты по фиксированной процентной ставке",
     "en":"Application for a fixed-rate loan secured by foreign currency collateral"},
    {"uz":"Тижорат банкининг Марказий банкдан чет эл валютасини гаров сифатида қўйиб, қайта молиялаш кредити олиш учун топшириладиган аризаси.",
     "ru":"Заявление коммерческого банка в Центральный банк о получении кредита рефинансирования под залог иностранной валюты.",
     "en":"An application by a commercial bank to the Central Bank for a refinancing loan secured by pledged foreign currency."},
    False),
"257.json": ("inheritance", "inheritance_acceptance_application",
    {"uz":"Мерос мол-мулкни қабул қилиш тўғрисидаги ариза","ru":"Заявление о принятии наследственного имущества","en":"Application for acceptance of inheritance property"},
    {"uz":"Марҳумнинг қонуний меросхўри томонидан мерос мол-мулкка нисбатан ҳуқуқ гувоҳномаси олиш учун нотариусга берилувчи ариза.",
     "ru":"Заявление, подаваемое законным наследником нотариусу для получения свидетельства о праве на наследственное имущество.",
     "en":"An application filed by a lawful heir with a notary to obtain a certificate of inheritance rights over the deceased's property."},
    False),
"258.json": ("finance", "pawnshop_credit_application",
    {"uz":"Ўзгармас фоиз ставка бўйича ломбард кредитини олиш тўғрисида ариза","ru":"Заявление на получение ломбардного кредита по фиксированной ставке","en":"Application for a fixed-rate lombard (pawn) credit"},
    {"uz":"Тижорат банкининг давлат қимматли қоғозларини гаровга қўйиб Марказий банкдан ломбард кредити олиш учун топширадиган аризаси.",
     "ru":"Заявление коммерческого банка в Центральный банк о получении ломбардного кредита под залог государственных ценных бумаг.",
     "en":"An application by a commercial bank to the Central Bank for a lombard loan secured by government securities."},
    False),
"259.json": ("inheritance", "secret_will_opening_protocol",
    {"uz":"Махфий васиятномани очиш ва ошкор қилиш баённомаси","ru":"Протокол вскрытия и оглашения закрытого завещания","en":"Protocol for opening and disclosing a closed (secret) will"},
    {"uz":"Васият қилувчи вафотидан сўнг нотариус томонидан гувоҳлар иштирокида махфий васиятнома хатжилдини очиш ва мазмунини ошкор қилиш жараёнини қайд этувчи баённома.",
     "ru":"Протокол, фиксирующий процесс вскрытия нотариусом конверта с закрытым завещанием и оглашения его содержания в присутствии свидетелей после смерти завещателя.",
     "en":"A protocol recording a notary's opening of a sealed closed-will envelope and disclosure of its contents before witnesses after the testator's death."},
    False),
"260.json": ("administrative", "public_event_permit_application",
    {"uz":"Оммавий тадбирни ўтказишга рухсатнома бериш тўғрисида ариза","ru":"Заявление о выдаче разрешения на проведение массового мероприятия","en":"Application for a permit to hold a public/mass event"},
    {"uz":"Ташкилотчи томонидан оммавий тадбирнинг мақсади, ўтказилиш жойи, вақти ва иштирокчилари тўғрисида маълумот бериб, ваколатли органдан рухсат сўраладиган ариза.",
     "ru":"Заявление организатора с указанием цели, места, времени и числа участников мероприятия, подаваемое уполномоченному органу для получения разрешения.",
     "en":"An application by an event organizer providing details on purpose, venue, timing, and participants, requesting a permit from the authorized body."},
    False),
"264.json": ("inheritance", "will_disinherit_legal_heirs_apartment",
    {"uz":"Қонун бўйича меросхўрларни меросдан маҳрум қилиш шарти билан васиятнома (уй-жой учун)",
     "ru":"Завещание квартиры с условием лишения наследства законных наследников",
     "en":"Will bequeathing an apartment while disinheriting statutory heirs"},
    {"uz":"Васият қилувчи ўз уй-жойини бошқа шахсга васият қилиб, шу билан бирга қонун бўйича барча меросхўрларини меросдан маҳрум қилувчи нотариал васиятнома.",
     "ru":"Нотариальное завещание, по которому завещатель передаёт квартиру постороннему лицу, одновременно лишая наследства всех законных наследников.",
     "en":"A notarized will bequeathing the testator's apartment to another person while disinheriting all statutory heirs."},
    False),
"265.json": ("inheritance", "will_all_property_to_relative",
    {"uz":"Барча мол-мулкни қариндошга васият қилиш тўғрисида васиятнома","ru":"Завещание всего имущества в пользу родственника","en":"Will bequeathing all property to a relative"},
    {"uz":"Васият қилувчи эгалик қиладиган барча мол-мулкини бир қариндошига мерос қилиб қолдирувчи оддий нотариал васиятнома.",
     "ru":"Простое нотариальное завещание, по которому завещатель передаёт всё принадлежащее ему имущество одному родственнику.",
     "en":"A straightforward notarized will bequeathing all of the testator's property to a single named relative."},
    False),
"266.json": ("vehicle", "vehicle_registration_power_of_attorney",
    {"uz":"Автомашинани бириктирилган ташкилот номига расмийлаштиришга ишончнома","ru":"Доверенность на переоформление автомашины на баланс организации","en":"Power of attorney for re-registering a vehicle to an organization's balance"},
    {"uz":"Юқори ташкилот томонидан бириктирилган автомашинани қуйи ташкилот номига расмийлаштириш ишларини амалга ошириш учун вакилга берилувчи ишончнома.",
     "ru":"Доверенность, выдаваемая представителю на выполнение действий по переоформлению автомашины, закреплённой вышестоящей организацией, на баланс подведомственной организации.",
     "en":"A power of attorney authorizing a representative to complete the paperwork transferring a vehicle assigned by a parent organization onto a subordinate organization's balance."},
    False),
"267.json": ("inheritance", "will_apartment_split_children",
    {"uz":"Уй-жойни икки фарзандга тенг ҳиссада васият қилиш тўғрисида васиятнома","ru":"Завещание квартиры в равных долях двум детям","en":"Will bequeathing an apartment equally to two children"},
    {"uz":"Васият қилувчининг уй-хонадонини икки фарзандига тенг улушларда мерос қилиб қолдиришини белгиловчи нотариал васиятнома.",
     "ru":"Нотариальное завещание, по которому квартира завещателя переходит в равных долях двум его детям.",
     "en":"A notarized will under which the testator's apartment passes in equal shares to their two children."},
    False),
"273.json": ("loan", "personal_loan_agreement",
    {"uz":"Қарз шартномаси (жисмоний шахслар ўртасида)","ru":"Договор займа между физическими лицами","en":"Personal loan agreement between individuals"},
    {"uz":"Қарз берувчи ва қарз олувчи ўртасида пул суммасини қарзга бериш, қайтариш муддати ва тарафлар мажбуриятларини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор между заимодавцем и заёмщиком, определяющий сумму займа, срок возврата и обязанности сторон.",
     "en":"A notarized contract between a lender and a borrower setting the loan amount, repayment deadline, and obligations of both parties."},
    False),
"275.json": ("court", "civil_appeal_complaint",
    {"uz":"Фуқаролик ишлари бўйича апелляция шикояти","ru":"Апелляционная жалоба по гражданскому делу","en":"Appellate complaint in a civil case"},
    {"uz":"Биринчи инстанция суди ҳал қилув қарорининг бекор қилинишини сўраб апелляция инстанциясига берилувчи шикоят.",
     "ru":"Жалоба, подаваемая в апелляционную инстанцию с просьбой отменить решение суда первой инстанции.",
     "en":"A complaint filed with the appellate court requesting reversal of a first-instance court's decision."},
    False),
"279.json": ("real_estate", "unfinished_house_sale_agreement",
    {"uz":"Қурилиши тугалланмаган уй-жойнинг олди-сотди шартномаси","ru":"Договор купли-продажи недостроенного дома","en":"Sale agreement for an unfinished (under-construction) house"},
    {"uz":"Қурилиш ишлари тугалланмаган уй-жой объектини мавжуд ҳолатда сотиш шартлари ва баҳосини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор, определяющий условия и цену продажи объекта недостроенного дома в его текущем состоянии.",
     "en":"A notarized contract setting the terms and price for selling an unfinished house in its current state of construction."},
    False),
"280.json": ("loan", "vehicle_pledge_amendment_agreement",
    {"uz":"Гаров шартномасига ўзгартириш киритиш ҳақида келишув","ru":"Соглашение о внесении изменений в договор залога","en":"Agreement amending a vehicle pledge contract"},
    {"uz":"Кредит таъминоти учун гаровга қўйилган автотранспорт воситалари алмаштирилганда амалдаги гаров шартномасига ўзгартириш киритиш тартибини белгилайдиган келишув.",
     "ru":"Соглашение, устанавливающее порядок внесения изменений в действующий договор залога при замене заложенных автотранспортных средств, обеспечивающих кредит.",
     "en":"An agreement establishing the procedure for amending an existing pledge contract when the vehicles securing a loan are replaced."},
    False),
"282.json": ("construction", "shared_construction_apartment_agreement",
    {"uz":"Кўп квартирали уй қурилишида улуш иштироки шартномаси (хонадон сотиб олиш)",
     "ru":"Договор долевого участия в строительстве многоквартирного дома (покупка квартиры)",
     "en":"Shared-equity construction agreement for purchasing an apartment"},
    {"uz":"Қурувчи ташкилот билан улушдор ўртасида қурилаётган уйда хонадон сотиб олиш, тўлов жадвали ва ички қурилиш ишлари шартларини белгилайдиган шартнома.",
     "ru":"Договор между застройщиком и дольщиком, определяющий условия покупки квартиры в строящемся доме, график платежей и объём внутренних отделочных работ.",
     "en":"A contract between a developer and a shareholder setting terms for purchasing an apartment under construction, payment schedule, and interior work scope."},
    False),
"283.json": ("court", "court_decision_enforcement_application",
    {"uz":"Ижро ҳужжатини ижро этиш тўғрисида ариза (Мажбурий ижро бюросига)","ru":"Заявление об исполнении исполнительного документа (в Бюро принудительного исполнения)","en":"Application to enforce a writ of execution (to the Enforcement Bureau)"},
    {"uz":"Иқтисодий суднинг ҳал қилув қарорига асосан берилган ижро варақасини ижрога қабул қилиш ва қарздордан суммани ундиришни сўраб Мажбурий ижро бюросига берилувчи ариза.",
     "ru":"Заявление в Бюро принудительного исполнения о принятии к производству исполнительного листа, выданного на основании решения экономического суда, и взыскании суммы с должника.",
     "en":"An application to the Enforcement Bureau requesting acceptance of a writ of execution issued under an economic court ruling and collection of the debt from the debtor."},
    False),
"288.json": ("real_estate", "house_exchange_agreement",
    {"uz":"Уй-жойларни айирбошлаш шартномаси","ru":"Договор мены жилых домов","en":"House exchange agreement"},
    {"uz":"Икки тараф ўртасида ўзларига тегишли уй-жойларни ўзаро айирбошлаш шартлари, майдонлари ва баҳосини белгилайдиган нотариал шартнома.",
     "ru":"Нотариальный договор, определяющий условия, площади и оценочную стоимость взаимного обмена жилыми домами между двумя сторонами.",
     "en":"A notarized contract setting the terms, areas, and valuation for two parties exchanging houses they own."},
    False),
"292.json": ("inheritance", "inheritance_renunciation_application",
    {"uz":"Меросхўрнинг мерос улушидан воз кечиш ҳақидаги аризаси","ru":"Заявление наследника об отказе от доли наследства","en":"Heir's application renouncing their share of the inheritance"},
    {"uz":"Меросхўрнинг ўзига тегишли мерос улушидан бошқа меросхўр фойдасига воз кечганлигини нотариусга билдирувчи ариза.",
     "ru":"Заявление наследника нотариусу об отказе от причитающейся ему доли наследства в пользу другого наследника.",
     "en":"An application by an heir notifying a notary of their renunciation of their inheritance share in favor of another heir."},
    False),
"293.json": ("finance", "lombard_credit_auction_application",
    {"uz":"Марказий банк ломбард кредити кимошди савдосида иштирок этиш учун ариза","ru":"Заявление на участие в аукционе ломбардных кредитов Центрального банка","en":"Application to participate in the Central Bank's lombard credit auction"},
    {"uz":"Тижорат банкининг Марказий банк ўтказадиган ломбард кредити кимошди савдосида иштирок этиш учун сўралаётган кредит ҳажми ва фоиз ставкасини кўрсатиб топшириладиган аризаси.",
     "ru":"Заявление коммерческого банка на участие в аукционе ломбардных кредитов Центрального банка с указанием запрашиваемого объёма и процентной ставки.",
     "en":"An application by a commercial bank to participate in the Central Bank's lombard credit auction, stating the requested loan volume and interest rate."},
    False),
"294.json": ("inheritance", "inheritance_renunciation_common_owners",
    {"uz":"Умумий мулкдорлар вафот этган тақдирда меросхўрнинг мерос улушидан воз кечиш ҳақидаги аризаси",
     "ru":"Заявление наследника об отказе от доли наследства в случае смерти совладельцев общего имущества",
     "en":"Heir's renunciation application when co-owners of joint property have both died"},
    {"uz":"Умумий мулкнинг иккала эгаси (масалан, ота-она) вафот этган тақдирда меросхўрнинг мерос улушидан ва янги мерос иши очиш ҳуқуқидан воз кечиш аризаси.",
     "ru":"Заявление наследника об отказе от наследственной доли и права на открытие нового наследственного дела в случае смерти обоих совладельцев общего имущества (например, родителей).",
     "en":"An heir's application renouncing their inheritance share and the right to open a new inheritance case when both co-owners of joint property (e.g., parents) have died."},
    False),
"296.json": ("real_estate", "residence_registration_application",
    {"uz":"Хонадонга доимий рўйхатга (пропискага) қўйиш тўғрисида ариза","ru":"Заявление о постоянной регистрации (прописке) в квартире","en":"Application for permanent residence registration in an apartment"},
    {"uz":"Уй-жой мулкдорининг фуқарони ва унинг оила аъзоларини ўз хонадонига доимий яшаш жойи бўйича рўйхатга олинишни сўраб берадиган аризаси.",
     "ru":"Заявление собственника жилья с просьбой зарегистрировать гражданина и членов его семьи по месту постоянного жительства в его квартире.",
     "en":"An application by a property owner requesting to register a citizen and their family members for permanent residence at the owner's apartment."},
    False),
"297.json": ("administrative", "apostille_application_individual",
    {"uz":"Жисмоний шахсга апостиль қўйиш тўғрисида ариза","ru":"Заявление физического лица о проставлении апостиля","en":"Application by an individual for affixing an apostille"},
    {"uz":"Жисмоний шахснинг чет давлатга тақдим этиладиган расмий ҳужжатларига апостиль қўйилишини сўраб берадиган аризаси.",
     "ru":"Заявление физического лица с просьбой проставить апостиль на официальных документах, предназначенных для предъявления за границей.",
     "en":"An application by an individual requesting an apostille be affixed to official documents intended for use abroad."},
    False),
"299.json": ("inheritance", "marital_property_share_certificate_joint_application",
    {"uz":"Эр-хотиннинг умумий мол-мулкидаги улушга бўлган мулк ҳуқуқи тўғрисида гувоҳнома бериш ҳақида қўшма ариза",
     "ru":"Совместное заявление супругов о выдаче свидетельства о праве на долю в общем имуществе",
     "en":"Joint spousal application for a certificate of ownership share in marital property"},
    {"uz":"Никоҳ давомида сотиб олинган ва бир томон номига расмийлаштирилган уй-жойга нисбатан икки томон улуш ҳуқуқини тасдиқловчи гувоҳнома сўраб иккала турмуш ўртоқ имзолаган ариза.",
     "ru":"Заявление, подписанное обоими супругами, с просьбой выдать свидетельство, подтверждающее долю каждого в жилье, купленном в браке и оформленном на одного из них.",
     "en":"An application signed by both spouses requesting a certificate confirming each one's share in housing purchased during marriage and registered to one spouse."},
    False),
"301.json": ("administrative", "notarial_document_duplicate_application",
    {"uz":"Нотариал ҳаракатдан дубликат бериш ҳақида ариза","ru":"Заявление о выдаче дубликата нотариального документа","en":"Application for a duplicate of a notarized document"},
    {"uz":"Илгари тасдиқланган нотариал ҳужжат (масалан, ишончнома) йўқолган ёки бошқа сабабга кўра дубликатини олиш учун нотариусга берилувчи ариза.",
     "ru":"Заявление, подаваемое нотариусу с просьбой выдать дубликат ранее удостоверенного нотариального документа (например, доверенности), утраченного по какой-либо причине.",
     "en":"An application filed with a notary requesting a duplicate of a previously certified notarial document (e.g., a power of attorney) lost for some reason."},
    False),
"369.json": ("court", "settlement_agreement_approval_application",
    {"uz":"Иқтисодий судда келишув битимини тасдиқлаш тўғрисида ариза","ru":"Заявление об утверждении мирового соглашения в экономическом суде","en":"Application to approve a settlement agreement in economic court"},
    {"uz":"Даъвогар билан жавобгар судда келишув битими тузганда, судга уни тасдиқлаш ва ишни тугатишни сўраб берилувчи ариза.",
     "ru":"Заявление в суд с просьбой утвердить мировое соглашение, заключённое истцом и ответчиком, и прекратить производство по делу.",
     "en":"An application to the court requesting approval of a settlement agreement reached between the plaintiff and defendant and termination of the case."},
    False),
"590.json": ("real_estate", "prisoner_apartment_sale_power_of_attorney",
    {"uz":"Жазони ижро этиш муассасасидаги маҳкум томонидан уй-жойни сотишга ишончнома","ru":"Доверенность на продажу квартиры, выданная осуждённым из исправительного учреждения","en":"Power of attorney to sell an apartment, issued by an inmate at a correctional facility"},
    {"uz":"Жазони ўтаётган маҳкумнинг ўзига тегишли уй-жойни сотиш ваколатини бошқа шахсга берувчи ва ЖИЭМ раҳбари томонидан тасдиқланувчи ишончнома.",
     "ru":"Доверенность осуждённого, отбывающего наказание, на продажу принадлежащей ему квартиры, удостоверяемая начальником исправительного учреждения.",
     "en":"A power of attorney by an inmate serving a sentence, authorizing another person to sell their apartment, certified by the correctional facility's head."},
    False),
"748.json": ("real_estate", "real_estate_sale_contract_general",
    {"uz":"Кўчмас мулкни сотиш шартномаси","ru":"Договор продажи недвижимого имущества","en":"General real estate sale contract"},
    {"uz":"Сотувчи ва сотиб олувчи ўртасида кўчмас мулк объектини топшириш муддати, баҳоси ва ҳисоб-китоб тартибини белгилайдиган умумий шаклдаги шартнома.",
     "ru":"Договор общего вида между продавцом и покупателем, определяющий срок передачи объекта недвижимости, его цену и порядок расчётов.",
     "en":"A general-form contract between a seller and buyer setting the handover deadline, price, and payment procedure for a real estate object."},
    False),
"876.json": ("family", "alimony_amount_change_lawsuit",
    {"uz":"Алимент миқдорини ўзгартириш ва қатъий суммада ундириш тўғрисида даъво аризаси",
     "ru":"Исковое заявление об изменении размера алиментов и взыскании в твёрдой денежной сумме",
     "en":"Lawsuit to change the alimony (child support) amount and collect it as a fixed sum"},
    {"uz":"Жавобгар даромадини яшириб, алиментни камроқ тўлаётганда, даъвогар томонидан алиментни ҳар ойда қатъий пул суммасида ундиришни сўраб судга берилувчи даъво аризаси.",
     "ru":"Исковое заявление в суд с просьбой взыскивать алименты в твёрдой денежной сумме ежемесячно, поскольку ответчик скрывает доходы и платит меньше положенного.",
     "en":"A lawsuit requesting the court to order monthly child support in a fixed sum, because the defendant is concealing income and paying less than owed."},
    False),
"1126.json": ("loan", "legal_entity_microloan_agreement",
    {"uz":"Юридик шахслар учун микроқарз шартномаси","ru":"Договор микрозайма для юридических лиц","en":"Microloan agreement for legal entities"},
    {"uz":"Банк ва юридик шахс қарз олувчи ўртасида микроқарз миқдори, фоиз ставкаси, қайтариш муддати ва тарафлар мажбуриятларини белгилайдиган шартнома.",
     "ru":"Договор между банком и заёмщиком - юридическим лицом, устанавливающий сумму микрозайма, процентную ставку, срок возврата и обязанности сторон.",
     "en":"A contract between a bank and a corporate borrower setting the microloan amount, interest rate, repayment term, and obligations of both parties."},
    False),
}

BATCH_FILE = r"C:\Users\vppfe\AppData\Local\Temp\claude\c--Users-vppfe-Desktop-Agreement-app\c207f2c0-10ea-4ffb-9cd6-e6629e6317eb\scratchpad\batch_01.txt"

with open(BATCH_FILE, "r", encoding="utf-8") as f:
    lines = [l.strip() for l in f if l.strip()]

batch_files = []
for l in lines:
    parts = l.split("\t")
    fname = parts[-1].strip()
    if fname.endswith(".json"):
        batch_files.append(fname)

processed = 0
low_conf = 0
errors = 0
manifest_lines = []

for fname in batch_files:
    if fname not in META:
        errors += 1
        manifest_lines.append(json.dumps({"source_file": fname, "error": "no metadata classification found"}, ensure_ascii=False))
        continue
    domain, key, title, desc, low_confidence = META[fname]
    src_path = os.path.join(SRC_DIR, fname)
    try:
        with open(src_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        errors += 1
        manifest_lines.append(json.dumps({"source_file": fname, "error": f"read error: {e}"}, ensure_ascii=False))
        continue

    new_data = {
        "domain": domain,
        "key": key,
        "title": title,
        "description": desc,
    }
    new_data.update(data)

    out_domain_dir = os.path.join(OUT_DIR, domain)
    os.makedirs(out_domain_dir, exist_ok=True)
    out_path = os.path.join(out_domain_dir, key + ".json")
    try:
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(new_data, f, ensure_ascii=False, indent=4)
    except Exception as e:
        errors += 1
        manifest_lines.append(json.dumps({"source_file": fname, "error": f"write error: {e}"}, ensure_ascii=False))
        continue

    rel_out = f"agreements/{domain}/{key}.json"
    entry = {
        "source_file": fname,
        "output_path": rel_out,
        "domain": domain,
        "key": key,
        "title_en": title["en"],
        "low_confidence": low_confidence,
    }
    manifest_lines.append(json.dumps(entry, ensure_ascii=False))
    processed += 1
    if low_confidence:
        low_conf += 1

with open(MANIFEST, "w", encoding="utf-8") as f:
    for line in manifest_lines:
        f.write(line + "\n")

print(f"Batch files: {len(batch_files)}")
print(f"Processed: {processed}")
print(f"Low confidence: {low_conf}")
print(f"Errors: {errors}")
